### ISSUE TITLE
Add Admin user

### ISSUE THREAD

**Issue by u21513768** [COS301-SE-2024/IoT-DIRfram#121]
Have it such that if a user is the first to add a raspberry pi device, they are determined to be the admin user of that pi and can therefore delete IoT pages from the IOT device page.

Possible edits include
- IoT device page
- Add device modal
- All relevant API calls
- Ability for users to ask for admin access as well as an external matter (eg, email)

**Comment by Yi-Rou1234** [comment]
in backend:
I edited: removeDeviceFromUser and deleteFile
components:
I edited: IOT_Device (handleDelete)
