### ISSUE TITLE
function to add a raspberry pi

### ISSUE THREAD

**Issue by CarterShin** [COS301-SE-2024/IoT-DIRfram#43]
add a raspberry pi via the serial number to the user that is logged in

**Comment by CarterShin** [comment]
when adding a raspberry pi, the username should be added with so that when they log back in we can check display their registered devices

**Comment by lloydcreighton** [comment]
Allowed to add a raspberry pi and to register user to raspberry pi API endpoints

**Comment by lloydcreighton** [comment]
Endpoints are /addDevice and /addDeviceToUser respectively
